In [1]:
import os

import pandas as pd

In [2]:
FILENAME = 'vocabulary_master.csv'

In [3]:
FILEPATH = os.path.join(os.getcwd(), FILENAME)

In [4]:
dataframe = pd.read_csv(FILEPATH, sep=';').sort_values(by='word').reset_index(drop=True)
dataframe.to_csv(FILEPATH, sep=';', index=False)
dataframe

,word,transcription,translation,success_number,learning_date
0,access,ˈækses,доступ,0,NaN
1,accumulating,əˈkjuːmjʊleɪtɪŋ,накапливающий,0,NaN
2,achieve,əˈʧiːv,"достигать, добиваться",0,NaN
3,achievements,əˈtʃiːvmənts,достижения,0,NaN
4,acquire,əˈkwaɪə,приобретать,0,NaN
...,...,...,...,...,...
195,verbatim,və:ˈbeɪtɪm,дословный,0,NaN
196,victory,ˈvɪkt(ə)ri,победа,0,NaN
197,warfare,ˈwɔː.feər,война,0,NaN
198,weigh up,weɪ ʌp,"взвесить, решить",0,NaN
199,émigré,ˈemɪɡreɪ,эмигрант,0,NaN